language: R
cache: packages

pandoc_version: 2.3.1

bioc_packages:
  GEOquery
  
r_github_packages:
  mcanouil/NACHO

script: Rscript -e 'rmarkdown::render(input = "NACHO.Rmd")'

before_deploy: Rscript -e 'remotes::install_cran("pkgdown")'

deploy:
  provider: script
  script: Rscript -e 'source("https://raw.githubusercontent.com/mcanouil/DEV/master/R/deploy.R"); deploy_site("NACHO.Rmd", dir_list = c("images"), commit_message = "NACHO_slides")'
  skip_cleanup: true

